{% set version = "2.4.1" %}
{% set cuda_major = environ.get("cuda_compiler_version", "0.0").split(".")[0]|int %}

package:
  name: muscat-split
  version: {{ version }}

source:
  url: https://gitlab.com/drti/muscat/-/archive/{{ version }}/muscat-{{ version }}.tar.bz2
  sha256: 80d0b27706f5811513a419fb97be4608770835343e667fb6e360eda1c20f8678

build:
  number: 2
  string: "cuda{{ cuda_major }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"  # [cuda_compiler_version != "None"]
  string: "cpu{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"  # [cuda_compiler_version == "None"]

outputs:
  - name: muscat-core
    version: {{ version }}
    script: build_core.sh      # [linux]
    script: build_core_OsX.sh  # [osx]
    script: bld_core.bat       # [win]

    build:
      script_env:
        - Muscat_CUDA_ARGS=-DMuscat_ENABLE_CUDA=ON  # [cuda_compiler_version != "None"]
        - Muscat_CUDA_ARGS=-DMuscat_ENABLE_CUDA=OFF  # [cuda_compiler_version == "None"]
      entry_points:
        - "MeshFileConvert = Muscat.IO.MeshFileConverter:Main"
      skip_compile_pyc:
        - "MuscatParaViewPlugin.py"
      missing_dso_whitelist:
        - "*/nvcuda.dll"   # [win]
        - "*/libcuda.so.1"   # [not win]

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - ninja                                  # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
        - cmake
      host:
        - ninja
        - python
        # for the moment numpy 2 is activated only for python 3.13 (numpy 1 not available on py 3.13)
        - numpy >=2.*  # [py >= 313]
        - numpy =1.*  # [py < 313]
        - cython
        - sympy
        - eigency
        - mkl-devel
        - setuptools-scm
        - eigen
        - libboost-headers
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
        - pip
        - tbb
        - tbb-devel
        - setuptools

        # mmg software api changes can break the bridge (for version)
        - mmgsuite =5.8
        - libscotch          # [not win]
        #so cmake can be tested before install
        - zlib
        - scipy >=1.12
        - dill
        - pywin32
        - networkx >=3.0
        # cvxpy not available in osx for numpy 2 (numpy 1 not available on python 3.13)
        - cvxpy  # [not osx or py!=313 ]
        - h5py
        - matplotlib-base
        - pycgns-core  # [py > 39]
        - pycgns  # [py == 39]
        - mumps-seq  # [not osx]
        - mumps-include  # [linux]

        # kokkos 4.6 is only available on linux
        - kokkos >=4.6.00 h*  # [linux and cuda_compiler_version == "None"]
        - kokkos >=4.6.00 cuda*  # [linux and cuda_compiler_version != "None"]
        - kokkos =4.4.01 h*  # [not linux]
  # Will get nvcc linker warnings if the cudatoolkit version doesn't match
        - cuda-version {{ environ.get("cuda_compiler_version") }}.*  # [cuda_compiler_version != "None"]
{% if cuda_major == 11 %}
        - cudatoolkit {{ environ.get("cuda_compiler_version") }}.*
{% endif %}
{% if cuda_major == 12 %}
        - cuda-cudart-dev
        - cuda-driver-dev  # [not win]
{% endif %}
      run:
        - python
        - __cuda  # [cuda_compiler_version != "None"]
        - {{ pin_compatible('numpy') }}
        - scipy >=1.12
        - sympy
        - eigency
        - networkx >=3.0
        - tbb
        - dill
        - pywin32  # [win]
        - kokkos >=4.6.00 h*  # [linux and cuda_compiler_version == "None"]
        - kokkos >=4.6.00 cuda*  # [linux and cuda_compiler_version != "None"]
        - kokkos =4.4.01 h*  # [not linux]
        - mmgsuite =5.8
    test:
      requires:
        - scipy
        - cvxpy  # [not osx or py!=313 ]
        - h5py
        - matplotlib-base
        # pycngs-core only available for python 3.10+
        - pycgns-core  # [py > 39]
        - pycgns  # [py == 39]
        - mumps-seq   # [not osx]
        - ffmpeg =7.0.*  # [win]

      imports:
        - Muscat
      commands:
        - python -u -m Muscat.Helpers.Check -k Which -k Mumps  # [osx]
        - python -u -m Muscat.Helpers.Check  # [linux]
        - python -u -m Muscat.Helpers.Check -k AnisotropicMetricComputation -k Mumps  # [win]

  - name: "muscat-extensions"
    version: {{ version }}
    requirements:
      host:
        - python
        - numpy >=2.*  # [py >= 313]
        - numpy =1.*  # [py < 313]
        - vtk
        - psutil
        - h5py
        - meshio
        - pyvista
        - networkx >=3.0
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - vtk
        - psutil
        - h5py
        - meshio
        - pyvista
        - networkx >=3.0
        - mmgsuite =5.8
        - cvxpy  # [not osx or py!=313 ]
        - pycgns-core  # [py > 39]
        - pycgns  # [py == 39]
        - mumps-seq   # [not osx]
    test:
      imports:
        - psutil
        - h5py
        - meshio
        - networkx

  - name: "muscat"
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage('muscat-core', max_pin='x.x.x') }}
        - {{ pin_subpackage('muscat-extensions', max_pin='x.x.x') }}
    test:
      imports:
        - Muscat
      commands:
        - python -u -m Muscat.Helpers.Check -k Which  # [osx]
        - python -u -m Muscat.Helpers.Check  # [linux]
        - python -u -m Muscat.Helpers.Check -k AnisotropicMetricComputation   # [win]

  - name: "muscat-devenv"
    version: {{ version }}
    requirements:
      run:
        - {{ compiler('cxx') }}
        - python
        - numpy >=2.*  # [py >= 313]
        - numpy =1.*  # [py < 313]
        - sympy
        - cython
        - eigency
        - mkl-devel
        - setuptools-scm
        - eigen
        - scipy >=1.9
        - h5py
        - networkx >=3.0
        - libboost-headers
        - pytest
        - vtk
        - tbb
        - tbb-devel
        - matplotlib-base
        - coverage
        - pywin32  # [win]
        - ffmpeg=7.0  # [win]
        - dill
        - cmake
        - kokkos >=4.6.00 h*  # [linux and cuda_compiler_version == "None"]
        - kokkos >=4.6.00 cuda*  # [linux and cuda_compiler_version != "None"]
        - kokkos =4.4.01 h*  # [not linux]
        - mmgsuite =5.8
        - pycgns-core  # [py > 39]
        - pycgns  # [py == 39]
        - cvxpy  # [not osx or py!=313 ]
    test:
      imports:
        - numpy

about:
  home: https://gitlab.com/drti/muscat
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Tools for finite element computations

extra:
  recipe-maintainers:
    - fbordeu
    - laureleen06
