github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github_actions:
  self_hosted: true
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
test: native
build_platform:
  linux_aarch64: linux_64
#  linux_ppc64le: linux_64
#  osx_arm64: osx_64
